### ISSUE TITLE
"pick from" options in settings don't work

### ISSUE THREAD

**Issue by jathek** [easonwong-de/Adaptive-Tab-Bar-Color#47]
![image](https://user-images.githubusercontent.com/692914/226155461-76d02f0d-9014-4511-90bb-ea08bb0428cb.png)
![image](https://user-images.githubusercontent.com/692914/226155474-5fe195f3-a739-460b-9be0-8ee76c32e492.png)
![image](https://user-images.githubusercontent.com/692914/226155487-c1628d04-bf3b-4c24-a09a-35ca0814b31a.png)

Trying to use "pick from id" as an option, but the tab is still red instead of black, even though the id color is `rgba(0,0,0,.6)`. Am I using this correctly? Trying to "pick from class" or "pick from tag" doesn't work either.

**Comment by easonwong-de** [comment]
@jathek As for now, the add-on will ignore the specified element if it’s not opaque.

**Comment by jathek** [comment]
> @jathek As for now, the add-on will ignore the specified element if it’s not opaque.

It doesn't work even when setting "pick from tag" to be `body`
![image](https://user-images.githubusercontent.com/692914/226869078-6f06a9ea-f65b-44f5-8d0b-b477cfeeb730.png)

**Comment by jathek** [comment]
While you are fixing this, the "specify a color" option also needs work. When trying to enter a custom RGB color, only the first digit typed is saved. I had to reopen the color picker many times to type all the digits for each color channel.

**Comment by easonwong-de** [comment]
@jathek In the latest patch v1.7.5, all “pick from *” options are transformed into one “use query selector” option, which will provide more functionalities. Old settings should be able to be automatically translated into query selector syntax, except for “pick from class” and “pick from tag” rules might be mixed up.

Regarding the issue with “specify a color”, I couldn’t replicate the problem yet, because I’m using macOS and its built-in colour picker always gets the job done. If I recall right, you couldn’t enter RGB values in the colour picker on Windows. Are you using Linux? Either way, I’m curious about how do you enter RGB values so that I can try to fix the issue.

**Comment by jathek** [comment]
I'm using Windows 10. Here's what happens when I try to set RGB values. Only the first digit is recorded every time I save the color-picker.

<video src="https://user-images.githubusercontent.com/692914/227706606-f13e7d5c-1cf6-408f-8f1c-a3002ed5a068.mp4" style="width:100%"></video>

**Comment by easonwong-de** [comment]
@jathek I see. The colour picker is different from the one on Windows 11. It might be Mozilla’s bug, but I’ll still try to address the issue.

By the way, because of the bug where “pick from tag” and “pick from class” got mixed up, some settings stored are not correct, e.g. you may change the settings for `cider.sh` to `body` instead of `.body`.

Once again, thank you for the testing and the screen record. It helps a lot!

**Comment by easonwong-de** [comment]
The colour picker bug is specifically mentioned in #49. Thus, this issue will be closed.
